// Custom AMD-like shim script to provide `require` and `define`
// Script load order matters, no circular dependencies yet

const __MODULE_CACHE__ = {};
const __MODULE_MAIN__ = Symbol();

// Require is a simple lookup in the module cache, no async support yet
const require = (name) => __MODULE_CACHE__[name];

const define = (...args) => {
  let name, deps, factory;

  // Lookup for names currently generated by umd-react
  const nameLookup = (name) =>
    ({
      JsxRuntime: "react/jsx-runtime",
      React: "react",
      ReactDOM: "react-dom",
    })[name] || name;

  // Parse the arguments for named or anonymous modules
  if (args.length === 3) {
    name = nameLookup(args[0]);
    deps = args[1];
    factory = args[2];
  } else {
    if (__MODULE_CACHE__[__MODULE_MAIN__]) {
      throw new Error("Only one main module is allowed.");
    } else {
      name = __MODULE_MAIN__;
      deps = args[0];
      factory = args[1];
    }
  }

  // Run the module factory with all deps, and add to the cache
  if (deps[0] === "require" && deps[1] === "exports") {
    __MODULE_CACHE__[name] = factory.call(
      this,
      require,
      {},
      ...deps.slice(2).map((dep) => __MODULE_CACHE__[dep]),
    );
  } else {
    __MODULE_CACHE__[name] = factory.call(
      this,
      ...deps.map((dep) => __MODULE_CACHE__[dep]),
    );
  }
};

define.amd = true; // lol no it's not, but pretend we are AMD/RequireJS
