// PROTOTYPE: Custom define script
// Module load order matters! This is not "asynchronous" compatible yet

const _ANONYMOUS_MODULE = Symbol();
const _GLOBAL_MODULE_CACHE = {};

const define = (...args) => {
    // Deps is ignored because it's not asynchronous
    let name, deps, factory;

    // Lookup for names currently generated by umd-react
    const nameLookup = (name) => ({
        "JsxRuntime": "react/jsx-runtime",
        "React": "react",
        "ReactDOM": "react-dom",
    })[name] || name;

    // Parse the arguments for named or anonymous modules
    if (args.length === 3) {
        name = nameLookup(args[0]);
        deps = args[1];
        factory = args[2];
    } else {
        if (_GLOBAL_MODULE_CACHE[_ANONYMOUS_MODULE]) {
            throw new Error("Only one anonymous module is allowed.")
        } else {
            name = _ANONYMOUS_MODULE;
            deps = args[0];
            factory = args[1];
        }
    }

    // Initialize the module and get the exports
    _GLOBAL_MODULE_CACHE[name] = factory(function (package) {
        return _GLOBAL_MODULE_CACHE[package];
    });
    
}

define.amd = true; // lol no it's not, but pretend we are AMD/RequireJS
